config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :qualifications

  resources :experiences

  resources :educations

  resources :activities
  
  resources :statics
  
  root :to => "statics#index"
  get '/dashboard' => 'statics#dashboard'

end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]

  # GET /qualifications
  # GET /qualifications.json
  def index
    @qualifications = Qualification.all
  end

  # GET /qualifications/1
  # GET /qualifications/1.json
  def show
  end

  # GET /qualifications/new
  def new
    @qualification = Qualification.new
  end

  # GET /qualifications/1/edit
  def edit
  end

  # POST /qualifications
  # POST /qualifications.json
  def create
    @qualification = Qualification.new(qualification_params)

    respond_to do |format|
      if @qualification.save
        format.html { redirect_to @qualification, notice: 'Qualification was successfully created.' }
        format.json { render :show, status: :created, location: @qualification }
      else
        format.html { render :new }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualifications/1
  # PATCH/PUT /qualifications/1.json
  def update
    respond_to do |format|
      if @qualification.update(qualification_params)
        format.html { redirect_to @qualification, notice: 'Qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualification }
      else
        format.html { render :edit }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualifications/1
  # DELETE /qualifications/1.json
  def destroy
    @qualification.destroy
    respond_to do |format|
      format.html { redirect_to qualifications_url, notice: 'Qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualification_params
      params.require(:qualification).permit(:description)
    end
end

app/helpers/qualifications_helper.rb
module QualificationsHelper
end

app/views/qualifications/_form.html.erb
<%= form_for(@qualification) do |f| %>
  <% if @qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

      <ul>
      <% @qualification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualifications/edit.html.erb
<h1>Editing qualification</h1>

<%= render 'form' %>

<%= link_to 'Show', @qualification %> |
<%= link_to 'Back', qualifications_path %>

app/views/qualifications/index.html.erb
<h1>Listing qualifications</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualifications.each do |qualification| %>
      <tr>
        <td><%= qualification.description %></td>
        <td><%= link_to 'Show', qualification %></td>
        <td><%= link_to 'Edit', edit_qualification_path(qualification) %></td>
        <td><%= link_to 'Destroy', qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualification', new_qualification_path %>

app/views/qualifications/new.html.erb
<h1>New qualification</h1>

<%= render 'form' %>

<%= link_to 'Back', qualifications_path %>

app/views/qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @qualification.description %>
</p>

<%= link_to 'Edit', edit_qualification_path(@qualification) %> |
<%= link_to 'Back', qualifications_path %>