config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :qualifications

  resources :experiences

  resources :educations

  resources :activities
  
  resources :statics
  
  root :to => "statics#index"
  get '/dashboard' => 'statics#dashboard'

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
    # The boolean is there to avoid duplication of titles in the index page.
    @user = "Adam Yi"
    @educations = Education.all
    @edu = true
    @experiences = Experience.all
    @exp = true
    @activities = Activity.all
    @act = true
    @qualifications = Qualification.all
    @qual = true
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/dashboard.html.erb
<h1>Resume Dashboard</h1>
<p><%= link_to 'Work Experiences', experiences_path %></p>
<p><%= link_to 'Education', educations_path %></p>
<p><%= link_to 'Activities and Projects', activities_path %></p>
<p><%= link_to 'Qualifications', qualifications_path %></p>

app/views/statics/index.html.erb
<h1><%= @user %> </h1>
<% ## Education %>
   <% if @educations.nil? %>
   <% else %>
     <% @educations.each do |edu| %>
       <% if @edu %>
         <h2>Education</h2>
         <% @edu = false %>
       <% end %>
         <%= edu.school %> | <%= edu.award %><br>
         <%= edu.location %> | <%= edu.date %><br>
         <%= edu.description %><br>
  <% end %>
  <% end %>
<% ## Education %>

<% ## Experience %>
  <% if @experiences.nil? %>
  <% else %>
    <% @experiences.each do |exp| %>
      <% if @exp %>
        <h2>Work experiences</h2>
          <% @exp = false %>
        <% end %>
          <%= exp.title %> | <%= exp.company %> | <%= exp.date %><br>
          <%= exp.description %><br>
  <% end %>
  <% end %>
<% ## Experience %>

<% ## Activities %>
  <% if @activities.nil? %>
  <% else %>
    <% @activities.each do |act| %>
      <% if @act %>
        <h2>Activities and Projects</h2>
        <% @act = false %>
      <% end %>
    <%= act.date %> | <%= act.title %> | <%= act.description %><br>
    <% end %>
  <% end %>
<% ## Activities %>

<% ## Qualifications %>
  <% if @qualifications.nil? %>
  <% else %>
    <% @qualifications.each do |qual| %>
      <% if @qual %>
        <h2>Qualifications</h2>
        <% @qual = false %>
      <% end %>
    <%= qual.description %><br>
    <% end %>
  <% end %>
<% ## Qualifications %>